### ISSUE TITLE
Serverless: Failure: API Gateway method does not appear to be setup for Lambda Proxy Integration

### ISSUE THREAD

**Issue by seunlanlege** [activescott/serverless-aws-static-file-handler#10] opened 2019-03-22 13:54 UTC
```
Serverless: GET / (λ: html)
Serverless: Failure: API Gateway method does not appear to be setup for Lambda Proxy Integration. Please confirm that `integration` property of the http event is not specified or set to `integration: proxy`. Missing lambda proxy property was isBase64Encoded
```

### steps to reproduce

run the demo included in this project

**Comment by activescott** [comment] 2019-03-23 16:59
Thank you for reporting! This sounds like an embarrassing bug. I’ll check it out soon and report back.

**Comment by chrisrothwell** [comment] 2019-05-26 09:47
I'm also getting this when running the Demo script in serverless-offline :-)

**Comment by activescott** [comment] 2019-05-29 06:20
I'm not able to reproduce this. Steps I took:

1. Clone repo
2. `cd ./demo`
3. `yarn deploy` 
Open the deployed URL in browser and it works. No errors shown via `yarn sls logs -f html`

I'm going to close the issue, but if you have a repo you can point to that reproduces the issue please do reopen it!

**Comment by evandrobalmant** [comment] 2019-06-24 20:27
Same error here, running local with the serverless-offline plugin. In the file StaticFileHandler.js I commented "isBase64Encoded" of the expectedProps array in the validateLambdaProxyIntegration method, it worked. I believe that serverless-offline does not pass this property to request

**Comment by activescott** [comment] 2019-06-27 07:42
Thanks for dropping a note @evandrobalmant ! Sounds like this is a bug specific to serverless-offline then. Do you happen to have a public repo that demonstrates the bug? 

P.S. I'd love to accept your pull request!

**Comment by activescott** [comment] 2019-07-08 03:40
I was able to repro when using serverless-offline:

Steps to repro:
1. Copy the demo files from https://github.com/activescott/serverless-aws-static-file-handler/tree/master/examples/basic into new `examples/offline` directory.
2. Rename package name to `static-file-handler-demo-offline` and serverless.yml service to `static-file-handler-demo-offline`
3. run `npm install`
4. run `npm install serverless-offline --save-dev`
5. add serverless-offline to `plugins` in serverless.yml so that it looks like:
    ```
    plugins:
      - serverless-offline
      - serverless-aws-static-file-handler/plugins/BinaryMediaTypes
    ```
6. run `./node_modules/.bin/serverless offline` and visit the site at `http://localhost:3000`

Note the console reports the following error:

> Serverless: Failure: API Gateway method does not appear to be setup for Lambda Proxy Integration. Please confirm that `integration` property of the http event is not specified or set to `integration: proxy`. Missing lambda proxy property was isBase64Encoded
> Error: API Gateway method does not appear to be setup for Lambda Proxy Integration. Please confirm that `integration` property of the http event is not specified or set to `integration: proxy`. Missing lambda proxy property was isBase64Encoded
>     at Function.validateLambdaProxyIntegration (/Users/scott/src/serverless-aws-static-file-handler/examples/offline/node_modules/serverless-aws-static-file-handler/StaticFileHandler.js:222:13)
>

**Comment by activescott** [comment] 2019-07-08 05:26
@seunlanlege, @chrisrothwell, @evandrobalmant Serverless-offline support now working as of v2.0.1 on NPM: https://www.npmjs.com/package/serverless-aws-static-file-handler

Also a working example in [examples/serverless-offline](https://github.com/activescott/serverless-aws-static-file-handler/tree/master/examples/serverless-offline). Thanks for reporting!

**Comment by evandrobalmant** [comment] 2019-07-10 15:56
Thanks @activescott, worked perfectly for files in the first level of the directory, but for subdirectory/file the path is transformed as urlencoded, for example "css/style.css" turned "css% 2Fstyle.css"

I have checked that in the get() method you use the property event.pathParameters[0], and I override the event object, as in the example.

```
module.exports.binary = async (event, context) => {
   event.pathParameters.proxy = event.path;
   return fileHandler.get (event, context)
}
```

For me ok, but would it be the appropriate point to check if you need to do "urldecoded" will be there in the requestPath on StaticFileHandler.get() ?

**Comment by activescott** [comment] 2019-07-12 06:52
I'll take a look at this in the coming days. 

I suspect we can simplify some of the lambda integration stuff checking at https://github.com/activescott/serverless-aws-static-file-handler/blob/master/src/StaticFileHandler.js#L70 since it is explicitly no longer supported (per https://github.com/activescott/serverless-aws-static-file-handler/blob/master/src/test/StaticFileHandler.js#L84).

Reopening for now.

**Comment by activescott** [comment] 2021-10-17 02:52
Hey gents. I tried to reproduce this today but couldn’t. Could someone please tell me how to reproduce this with the example? The example is at https://github.com/activescott/serverless-aws-static-file-handler/tree/main/examples/serverless-offline

I did make some changes to it today in an effort to make it exercise more of the code but I couldn’t reproduce it before or after the changes.

**Comment by flawiddsouza** [comment] 2021-11-09 07:24
Hi @activescott, I think this might be a different issue. We were getting stageVariables missing instead of isBase64Encoded when custom property was set in serverless.yml. This happens only when using serverless-offline and doesn't happen with live aws. Related issue in serverless-offline repo for reference: https://github.com/dherault/serverless-offline/issues/1201.

Issue does not happen if you have a older version of serverless-offline.

**Comment by activescott** [comment] 2021-12-22 05:29
I have checked again with the example at https://github.com/activescott/serverless-aws-static-file-handler/tree/main/examples/serverless-offline with serverless-offline version 8.3.1 (the latest available on npm at this moment) and still don't see any issues. If someone can update that example to repro the issue or tell me how to I'll be happy to take a look at a fix.

**Comment by activescott** [comment] 2022-02-09 04:14
Hey all I am closing this one as I am not able to reproduce it. However, if someone else can add a bit more info to help repro please feel free to re-open it with the details! Thanks for all of your feedback and help!

**Closed by activescott** 2022-02-09 04:14 UTC
Labels: invalid, question, cannot-reproduce
